### ISSUE TITLE
Admin boton sin accion

### ISSUE THREAD

**Issue by Nidev-lab** [Mausach/proyectoFinalRollingCodeFrontend#1]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario administrador.
3. Deshabilite alguno usuarios.
4. Quise volver a habilitarlos.

## Resultado esperado

• Poder habilitar y deshabilitar los usuarios sin problemas.

## Resultado actual

•El botón para habilitar nuevamente los usuarios no cumple ninguna funcion.

## Captura

![image](https://github.com/Mausach/proyectoFinalRollingCodeFrontend/assets/53904695/1bce8ae4-8afe-40ad-9c5c-d7cc5cffc152)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Mausach** [comment]
ya se realizo esta modificación
