### ISSUE TITLE
Scroll horizontal

### ISSUE THREAD

**Issue by Nidev-lab** [Mausach/proyectoFinalRollingCodeFrontend#2]
## Proceso

Ingrese a la pagina.

## Resultado esperado

Que no se encuentre scroll horizontal.

## Resultado actual

Se encuentra scroll horizontal.

## Captura

![image](https://github.com/Mausach/proyectoFinalRollingCodeFrontend/assets/53904695/c9cbebc8-91ba-4643-8636-afa0030823b0)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Mausach** [comment]
ya se realizo esta modificación
