### ISSUE TITLE
Problemas de responsividad

### ISSUE THREAD

**Issue by Nidev-lab** [Mausach/proyectoFinalRollingCodeFrontend#3]
## Proceso

1. Ingrese a la pagina.
2. Me dirigí a la sección "Nosotros".

## Resultado esperado

• Que no se encuentre scroll horizontal.

## Resultado actual

• Se encuentra scroll horizontal.

## Posible solucion 

•Agregar la class "img-fluid" a la imagen en cuestion.

## Captura

![image](https://github.com/Mausach/proyectoFinalRollingCodeFrontend/assets/53904695/69dce90b-949f-42c8-b673-b35a2e141947)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Mausach** [comment]
ya se realizo esta modificación
