### ISSUE TITLE
Error al dar de alta un usuario

### ISSUE THREAD

**Issue by Nidev-lab** [Mausach/proyectoFinalRollingCodeFrontend#4]
## Proceso

1. Ingrese a la pagina.
2. Me loguee como admin.
3. Quise agregar un user nuevo con el rol "Usuario"

## Resultado esperado

•Poder crear un user con el rol "usuario".

(Esto funciona bien cuando agrego un user nuevo con el rol "Admin", pero al momento que elijo el rol de "usuario" se genera dicho error)

## Resultado actual

• Al darle "guardar usuario" no pasa nada y genera errores en consola.

## Captura

![image](https://github.com/Mausach/proyectoFinalRollingCodeFrontend/assets/53904695/8b49229f-be35-4403-bc1d-bf8aac443bb5)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Mausach** [comment]
ya se realizo esta modificación
